import { useState, useCallback } from "react";
import { useVisiblePolling } from "../lib/useVisiblePolling";

interface Report {
  name: string;
  source: string;
  path: string;
  hasHtml: boolean;
  hasPdf: boolean;
  htmlPath: string | null;
  pdfPath: string | null;
  htmlSize: number;
  htmlMtime: string;
  pdfSize: number;
  pdfMtime: string;
}

function fmtSize(b: number) {
  if (!b) return "—";
  if (b < 1024) return `${b}B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)}K`;
  return `${(b / 1024 / 1024).toFixed(1)}M`;
}

function fmtDate(iso: string) {
  if (!iso) return "—";
  const d = new Date(iso);
  return d.toLocaleDateString([], { month: "short", day: "numeric" }) + " " + d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Report | null>(null);
  // We render the report through an <iframe src=…/view> now; no need to fetch HTML
  // into React state — the browser loads + caches it natively from the /view route.
  const [pdfBusy, setPdfBusy] = useState<string | null>(null);
  const [filter, setFilter] = useState<"all" | "ready" | "missing">("all");
  const [toast, setToast] = useState<{ text: string; ok: boolean } | null>(null);
  // Tracks the bulk "Generate All Missing" job — disables button + shows spinner while running
  const [bulkBusy, setBulkBusy] = useState(false);

  const fetchReports = useCallback(() => {
    setLoading(true);
    fetch("/api/reports")
      .then((r) => r.json())
      .then((d) => {
        const list: Report[] = d.reports || [];
        setReports(list);
        // Keep the open report in sync with fresh data so its iframe (keyed on htmlMtime)
        // reloads when the report is regenerated by an agent while it's selected.
        setSelected((cur) => (cur ? (list.find((x) => x.name === cur.name) || cur) : cur));
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  // Auto-refresh while the tab is visible so reports generated by agents/chat (outside this
  // page's own buttons) appear without a manual refresh. Fires once on mount + on re-focus.
  useVisiblePolling(fetchReports, 10000);

  // Selecting a report just sets the active row — the iframe handles loading the
  // actual HTML body itself via its src= URL, so no fetch is needed here.
  const loadContent = useCallback((r: Report) => {
    setSelected(r);
  }, []);

  const showToast = (text: string, ok: boolean) => {
    setToast({ text, ok });
    setTimeout(() => setToast(null), 4000);
  };

  const generatePdf = async (r: Report) => {
    setPdfBusy(r.name);
    try {
      const resp = await fetch(`/api/reports/${encodeURIComponent(r.name)}/pdf`, { method: "POST" });
      const data = await resp.json();
      if (resp.ok) {
        showToast(`✓ PDF generated for ${r.name} (${fmtSize(data.size)})`, true);
        fetchReports();
      } else {
        showToast(`✗ ${data.error || "PDF generation failed"}`, false);
      }
    } catch (e: any) {
      showToast(`✗ Request failed: ${e.message}`, false);
    }
    setPdfBusy(null);
  };

  const downloadFile = (r: Report, format: "html" | "pdf") => {
    // cache-bust by file mtime so a regenerated report downloads fresh, not a stale browser cache
    const v = encodeURIComponent((format === "pdf" ? r.pdfMtime : r.htmlMtime) || "");
    window.location.href = `/api/reports/${encodeURIComponent(r.name)}/download/${format}?v=${v}`;
  };

  // Open the report inline in a new browser tab so the user can scroll the full HTML
  // unconstrained by the in-app iframe. Goes through the /view endpoint which sets
  // Content-Disposition: inline so the browser renders rather than downloads.
  const openFullPage = (r: Report) => {
    if (!r.hasHtml) return;
    const v = encodeURIComponent(r.htmlMtime || "");
    window.open(`/api/reports/${encodeURIComponent(r.name)}/view?v=${v}`, "_blank", "noopener,noreferrer");
  };

  // Trigger backend bulk job: scan every engagement, kick off report generation for
  // any without an HTML report. Each child job lands in reportJobs and the page
  // refresh below will eventually reflect status as the agents finish.
  const generateAllMissing = async () => {
    const missingCount = reports.filter(r => !r.hasHtml).length;
    if (missingCount === 0) {
      showToast("No missing reports — everything is up to date.", true);
      return;
    }
    if (!confirm(`Queue report generation for ${missingCount} engagement(s)? Each one spawns a Claude agent and may take a few minutes.`)) {
      return;
    }
    setBulkBusy(true);
    try {
      const resp = await fetch("/api/reports/generate-missing", { method: "POST" });
      const data = await resp.json();
      if (resp.ok) {
        showToast(`✓ Queued ${data.queued} report job(s) · ${data.failed} failed to start`, data.queued > 0);
        // Stagger refreshes — first quick (to see the new "running" markers eventually
        // populate report files), then a longer one for completed runs.
        setTimeout(fetchReports, 8000);
        setTimeout(fetchReports, 30000);
        setTimeout(fetchReports, 120000);
      } else {
        showToast(`✗ ${data.error || "Bulk generation failed"}`, false);
      }
    } catch (e: any) {
      showToast(`✗ ${e.message}`, false);
    }
    setBulkBusy(false);
  };

  const generateReport = async (r: Report) => {
    setPdfBusy(r.name + "-gen");
    try {
      const resp = await fetch(`/api/engagements/${encodeURIComponent(r.name)}/generate-report`, { method: "POST" });
      const data = await resp.json();
      if (resp.ok) {
        showToast(`✓ Report generation started for ${r.name} (jobId ${data.jobId?.slice(-8)})`, true);
        // Refresh after a delay since this takes time
        setTimeout(fetchReports, 5000);
      } else {
        showToast(`✗ ${data.error || "Failed to start"}`, false);
      }
    } catch (e: any) {
      showToast(`✗ ${e.message}`, false);
    }
    setPdfBusy(null);
  };

  const filtered = reports.filter((r) => {
    if (filter === "ready") return r.hasHtml;
    if (filter === "missing") return !r.hasHtml;
    return true;
  });

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", minHeight: 0, position: "relative" }}>
      {/* Toast */}
      {toast && (
        <div style={{
          position: "absolute", top: 12, right: 12, zIndex: 100,
          padding: "8px 14px", borderRadius: 5, fontSize: 11, fontWeight: 600,
          background: toast.ok ? "rgba(43,212,127,0.15)" : "rgba(255,77,99,0.15)",
          border: `1px solid ${toast.ok ? "rgba(43,212,127,0.5)" : "rgba(255,77,99,0.5)"}`,
          color: toast.ok ? "var(--neon-green)" : "var(--neon-red, #ff4d63)",
          boxShadow: "0 4px 12px rgba(0,0,0,0.4)", maxWidth: 380,
        }}>
          {toast.text}
        </div>
      )}

      {/* Header */}
      <div style={{
        padding: "8px 12px", borderBottom: "1px solid var(--border-color)",
        display: "flex", justifyContent: "space-between", alignItems: "center", flexShrink: 0, gap: 8,
      }}>
        <div>
          <span style={{ fontSize: 11, fontWeight: 700, color: "var(--jarvis-blue)", letterSpacing: "0.06em" }}>
            ⊟ REPORTS
          </span>
          <span style={{ fontSize: 9, color: "var(--text-muted)", marginLeft: 8 }}>
            {reports.length} engagements · {reports.filter(r => r.hasHtml).length} with reports · {reports.filter(r => r.hasPdf).length} with PDF
          </span>
        </div>
        <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
          {(["all", "ready", "missing"] as const).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              style={{
                fontSize: 9, padding: "4px 10px", borderRadius: 4,
                border: `1px solid ${filter === f ? "rgba(182,242,58,0.5)" : "var(--border-color)"}`,
                background: filter === f ? "rgba(182,242,58,0.12)" : "transparent",
                color: filter === f ? "var(--jarvis-blue)" : "var(--text-muted)",
                cursor: "pointer", textTransform: "uppercase", letterSpacing: "0.04em",
              }}
            >
              {f}
            </button>
          ))}
          {/* Bulk generate — kicks off report-gen for every engagement without an HTML report.
              Disabled while a bulk job is in flight to prevent double-submission. */}
          <button
            onClick={generateAllMissing}
            disabled={bulkBusy}
            title="Queue Claude agents to generate a report for every engagement that is missing one"
            style={{
              fontSize: 9, padding: "4px 10px", borderRadius: 4,
              border: "1px solid rgba(255,174,66,0.5)",
              background: bulkBusy ? "rgba(255,174,66,0.05)" : "rgba(255,174,66,0.12)",
              color: "var(--neon-amber, #ffae42)", cursor: bulkBusy ? "wait" : "pointer",
              fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.04em",
              opacity: bulkBusy ? 0.6 : 1,
            }}
          >
            {bulkBusy ? "⟳ queuing…" : "⚡ Gen All Missing"}
          </button>
          <button onClick={fetchReports} style={{
            fontSize: 9, padding: "4px 10px", borderRadius: 4,
            border: "1px solid var(--border-color)", background: "transparent",
            color: "var(--text-muted)", cursor: "pointer", marginLeft: 4,
          }}>↻ Refresh</button>
        </div>
      </div>

      <div style={{ flex: 1, display: "flex", minHeight: 0 }}>
        {/* List */}
        <div style={{
          width: selected ? "38%" : "100%",
          borderRight: selected ? "1px solid var(--border-color)" : "none",
          overflowY: "auto", padding: 6, transition: "width 0.2s ease",
        }}>
          {loading ? (
            <div style={{ textAlign: "center", padding: 30, color: "var(--text-muted)", fontSize: 10 }}>Loading...</div>
          ) : filtered.length === 0 ? (
            <div style={{ textAlign: "center", padding: 30, color: "var(--text-muted)", fontSize: 10 }}>No engagements match this filter</div>
          ) : filtered.map((r) => (
            <div
              key={r.name}
              onClick={() => loadContent(r)}
              style={{
                padding: "8px 10px", marginBottom: 4, borderRadius: 6,
                cursor: "pointer",
                background: selected?.name === r.name ? "rgba(182,242,58,0.1)" : "rgba(0,0,0,0.2)",
                borderLeft: `3px solid ${r.hasHtml ? (r.hasPdf ? "var(--neon-green)" : "var(--jarvis-blue)") : "var(--text-muted)"}`,
                transition: "background 0.1s",
              }}
            >
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 6 }}>
                <div style={{ overflow: "hidden", flex: 1 }}>
                  <div style={{ fontSize: 11, fontWeight: 700, color: "var(--text-primary)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                    {r.name}
                  </div>
                  <div style={{ fontSize: 8, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" }}>
                    {r.source}
                  </div>
                </div>
                <div style={{ display: "flex", gap: 3, flexShrink: 0 }}>
                  {r.hasHtml && <span style={{ fontSize: 8, padding: "2px 6px", borderRadius: 3, background: "rgba(182,242,58,0.15)", border: "1px solid rgba(182,242,58,0.4)", color: "var(--jarvis-blue)", fontWeight: 700 }}>HTML</span>}
                  {r.hasPdf && <span style={{ fontSize: 8, padding: "2px 6px", borderRadius: 3, background: "rgba(43,212,127,0.15)", border: "1px solid rgba(43,212,127,0.4)", color: "var(--neon-green)", fontWeight: 700 }}>PDF</span>}
                  {!r.hasHtml && <span style={{ fontSize: 8, padding: "2px 6px", borderRadius: 3, background: "rgba(255,174,66,0.15)", border: "1px solid rgba(255,174,66,0.4)", color: "var(--neon-amber, #ffae42)", fontWeight: 700 }}>NO REPORT</span>}
                </div>
              </div>
              <div style={{ display: "flex", gap: 10, fontSize: 9, color: "var(--text-dim)", marginTop: 4 }}>
                {r.hasHtml && <span>HTML {fmtSize(r.htmlSize)} · {fmtDate(r.htmlMtime)}</span>}
                {r.hasPdf && <span>PDF {fmtSize(r.pdfSize)}</span>}
              </div>
            </div>
          ))}
        </div>

        {/* Detail panel */}
        {selected && (
          <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", minWidth: 0 }}>
            {/* Header */}
            <div style={{
              padding: "8px 12px", borderBottom: "1px solid var(--border-color)",
              display: "flex", justifyContent: "space-between", alignItems: "center", flexShrink: 0, gap: 8, flexWrap: "wrap",
            }}>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 12, fontWeight: 700, color: "var(--jarvis-blue)" }}>{selected.name}</div>
                <div style={{ fontSize: 9, fontFamily: "monospace", color: "var(--text-dim)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                  {selected.path}
                </div>
              </div>
              <div style={{ display: "flex", gap: 5, flexWrap: "wrap" }}>
                {!selected.hasHtml && (
                  <button
                    onClick={() => generateReport(selected)}
                    disabled={pdfBusy === selected.name + "-gen"}
                    style={{
                      fontSize: 10, padding: "5px 10px", borderRadius: 4,
                      border: "1px solid rgba(255,174,66,0.4)", background: "rgba(255,174,66,0.1)",
                      color: "var(--neon-amber, #ffae42)", cursor: "pointer", fontWeight: 600, minHeight: 28,
                    }}
                  >
                    {pdfBusy === selected.name + "-gen" ? "Starting..." : "⚡ Generate Report"}
                  </button>
                )}
                {selected.hasHtml && (
                  <>
                    {/* Full-page view — opens /api/reports/:name/view inline in a new tab so
                        the user reads the whole report unconstrained by the in-pane iframe */}
                    <button
                      onClick={() => openFullPage(selected)}
                      title="Open the full HTML report in a new tab"
                      style={{
                        fontSize: 10, padding: "5px 10px", borderRadius: 4,
                        border: "1px solid rgba(43,212,127,0.4)", background: "rgba(43,212,127,0.1)",
                        color: "var(--neon-green)", cursor: "pointer", fontWeight: 600, minHeight: 28,
                      }}
                    >
                      ⛶ Full Page
                    </button>
                    {/* Re-run generator — kept as "Rebuild" for existing reports so the wrap-CSS
                        fix can be applied to legacy reports without typing a CLI command */}
                    <button
                      onClick={() => generateReport(selected)}
                      disabled={pdfBusy === selected.name + "-gen"}
                      title="Re-run the Claude report generator (overwrites the current HTML — useful to apply new template styling)"
                      style={{
                        fontSize: 10, padding: "5px 10px", borderRadius: 4,
                        border: "1px solid rgba(255,174,66,0.4)", background: "rgba(255,174,66,0.1)",
                        color: "var(--neon-amber, #ffae42)", cursor: "pointer", fontWeight: 600, minHeight: 28,
                      }}
                    >
                      {pdfBusy === selected.name + "-gen" ? "Starting..." : "⟳ Regen"}
                    </button>
                    <button
                      onClick={() => generatePdf(selected)}
                      disabled={pdfBusy === selected.name}
                      style={{
                        fontSize: 10, padding: "5px 10px", borderRadius: 4,
                        border: "1px solid rgba(176,124,255,0.4)", background: "rgba(176,124,255,0.1)",
                        color: "#b07cff", cursor: "pointer", fontWeight: 600, minHeight: 28,
                      }}
                    >
                      {pdfBusy === selected.name ? "Generating..." : (selected.hasPdf ? "⟳ Rebuild PDF" : "📄 → PDF")}
                    </button>
                    <button
                      onClick={() => downloadFile(selected, "html")}
                      style={{
                        fontSize: 10, padding: "5px 10px", borderRadius: 4,
                        border: "1px solid rgba(182,242,58,0.4)", background: "rgba(182,242,58,0.1)",
                        color: "var(--jarvis-blue)", cursor: "pointer", fontWeight: 600, minHeight: 28,
                      }}
                    >
                      ⬇ HTML
                    </button>
                  </>
                )}
                {selected.hasPdf && (
                  <button
                    onClick={() => downloadFile(selected, "pdf")}
                    style={{
                      fontSize: 10, padding: "5px 10px", borderRadius: 4,
                      border: "1px solid rgba(43,212,127,0.4)", background: "rgba(43,212,127,0.1)",
                      color: "var(--neon-green)", cursor: "pointer", fontWeight: 600, minHeight: 28,
                    }}
                  >
                    ⬇ PDF
                  </button>
                )}
                <button onClick={() => { setSelected(null); }}
                  style={{ fontSize: 10, padding: "5px 8px", borderRadius: 4, border: "1px solid rgba(255,77,99,0.3)", background: "transparent", color: "var(--neon-red, #ff4d63)", cursor: "pointer", minHeight: 28 }}>
                  ✕
                </button>
              </div>
            </div>

            {/* Content — uses iframe src= against the /view endpoint instead of srcDoc.
                Why: srcDoc has no base URL, so relative paths like `assets/Logo.svg` in the
                report HTML break (404). With src= pointing at /api/reports/:name/view, the
                browser uses the URL as the base, the companion /assets/:file route resolves
                images correctly, and the report renders identically to the full-page tab. */}
            <div style={{ flex: 1, overflow: "auto", background: "#fff" }}>
              {!selected.hasHtml ? (
                <div style={{ padding: 30, color: "var(--text-muted)", fontSize: 11, textAlign: "center", background: "var(--bg-primary)" }}>
                  No report generated yet. Click <strong>⚡ Generate Report</strong> above to build one from the engagement files.
                </div>
              ) : (
                <iframe
                  src={`/api/reports/${encodeURIComponent(selected.name)}/view?v=${encodeURIComponent(selected.htmlMtime || "")}`}
                  sandbox="allow-same-origin allow-popups allow-popups-to-escape-sandbox"
                  style={{ width: "100%", height: "100%", border: "none", background: "#fff" }}
                  title={`${selected.name} report`}
                />
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
